#!/usr/bin/env python3
"""Fills Korean translations (and English plural variants) into dancove/Localizable.xcstrings.

Run after `xcstringstool sync` has added any new keys:
    python3 scripts/localize-ko.py
Keys without a translation are printed so they can be added here.
"""
import json
import pathlib
import sys

CATALOG = pathlib.Path(__file__).resolve().parent.parent / "dancove" / "Localizable.xcstrings"

KO = {
    "%@ %@ · Lv %lld": "%1$@ %2$@ · Lv %3$lld",
    "%@ evolved!": "%@ 진화!",
    "%@ joined your team!": "%@ 합류!",
    "%@ joined your team.": "새 동료: %@",
    "%@ · Lv %lld": "%1$@ · Lv %2$lld",
    "%lld caught · %lld seen / %lld": "%1$lld마리 잡음 · %2$lld마리 발견 / %3$lld",
    "About the data": "데이터 안내",
    "Add to Party": "파티에 넣기",
    "Adventure": "모험",
    "Adventure partner": "모험 파트너",
    "An unofficial, non-commercial fan feature, not affiliated with or endorsed by Nintendo, Game Freak, Creatures Inc. or The Pokémon Company. Pokémon and all related names are their trademarks.": "비공식·비상업 팬 기능이에요. Nintendo, Game Freak, Creatures Inc., The Pokémon Company와 관계가 없고 승인받지 않았어요. 포켓몬과 관련 이름은 모두 해당 회사의 상표예요.",
    "BOSS": "보스",
    "BOSS · Lv%lld": "보스 · Lv%lld",
    "Banners for catches, evolutions and bosses": "포획·진화·보스 알림 보기",
    "Battles go on while an agent works": "에이전트가 일하면 전투가 이어져요",
    "Beaten at %@, so training here first.": "%@에서 져서 여기서 먼저 훈련 중이에요.",
    "Boss %@ cleared!": "보스 %@ 클리어!",
    "Bug": "벌레",
    "Choose your partner": "파트너를 골라 주세요",
    "Couldn't reach PokéAPI": "PokéAPI에 연결할 수 없어요",
    "Critical hit!": "급소!",
    "Dark": "악",
    "Dragon": "드래곤",
    "Electric": "전기",
    "Empty": "빈 자리",
    "Fairy": "페어리",
    "Fighting": "격투",
    "Fire": "불꽃",
    "Flying": "비행",
    "Furthest stage": "최고 스테이지",
    "Getting Pokédex data…": "도감 데이터를 받는 중…",
    "Ghost": "고스트",
    "Go on an adventure": "모험 떠나기",
    "Grass": "풀",
    "Ground": "땅",
    "Ice": "얼음",
    "It became %@.": "새 모습: %@",
    "Keep your agents busy to meet this one.": "에이전트가 열심히 일하면 만날 수 있어요.",
    "Lead": "리더로",
    "Lv %lld": "Lv %lld",
    "Lv%lld": "Lv%lld",
    "Mythical": "환상",
    "Not very effective": "효과가 별로",
    "On to world %lld.": "월드 %lld로 출발!",
    "Open Pokédex": "도감 열기",
    "Party": "파티",
    "Party is full": "파티가 가득 찼어요",
    "Pick a Pokémon in the Pokédex to add it.": "도감에서 포켓몬을 골라 파티에 넣어 보세요.",
    "Play a sound for new Pokémon": "새 포켓몬을 잡으면 소리 내기",
    "Poison": "독",
    "Pokédex": "도감",
    "Pokémon adventure": "포켓몬 모험",
    "Pokémon data and sprites are downloaded from PokéAPI (pokeapi.co) while dancove runs and are cached on this Mac. None are bundled with dancove.": "포켓몬 데이터와 이미지는 dancove가 실행될 때 PokéAPI(pokeapi.co)에서 받아 이 Mac에 저장해요. dancove에는 들어 있지 않아요.",
    "Progress": "진행 상황",
    "Psychic": "에스퍼",
    "Rock": "바위",
    "Stage %@ cleared!": "스테이지 %@ 클리어!",
    "Stages cleared": "클리어한 스테이지",
    "Start Over": "처음부터",
    "Start Over…": "처음부터 다시…",
    "Start the adventure over?": "모험을 처음부터 다시 할까요?",
    "Steel": "강철",
    "Super effective!": "효과가 굉장해!",
    "The adventure starts once the Pokédex downloads.": "도감을 받으면 모험이 시작돼요.",
    "Training": "훈련 중",
    "Try Again": "다시 시도",
    "Water": "물",
    "While Claude or Codex works, your party of up to three battles through stages on its own. Finished turns can bring a wild Pokémon along. Bosses every ten stages decide how far you get.": "Claude나 Codex가 일하는 동안 최대 3마리 파티가 알아서 스테이지를 돌파해요. 작업이 끝나면 야생 포켓몬이 따라오기도 하고, 10스테이지마다 나오는 보스가 얼마나 멀리 갈 수 있을지 정해요.",
    "Your Pokémon, Pokédex and stage progress will be cleared. This can't be undone.": "포켓몬, 도감, 스테이지 진행이 모두 지워져요. 되돌릴 수 없어요.",
    "%lld items": "%lld개",
    "%lld pinned": "고정 %lld개",
    "%lldd": "%lld일",
    "Allow Accessibility for dancove to paste straight into apps.": "dancove에 손쉬운 사용을 허용하면 앱에 바로 붙여넣을 수 있어요.",
    "Clear": "지우기",
    "Clear %lld?": "%lld개 지울까요?",
    "Clear History": "기록 지우기",
    "Clear history": "기록 지우기",
    "Click again to clear. Pinned items stay.": "한 번 더 누르면 지워져요. 고정한 항목은 남아요.",
    "Clicking an item": "항목을 클릭하면",
    "Clipboard": "클립보드",
    "Copied": "복사됨",
    "Copies it": "복사",
    "Copy": "복사",
    "Copy something and it shows up here.": "무언가 복사하면 여기에 쌓여요.",
    "Image": "이미지",
    "Keep clipboard history": "클립보드 기록 보관",
    "Keep up to": "최대 보관 개수",
    "Passwords and anything an app marks as confidential are never saved. History stays on this Mac.": "암호와 앱이 기밀로 표시한 항목은 저장하지 않아요. 기록은 이 Mac에만 남아요.",
    "Passwords are never saved.": "암호는 저장하지 않아요.",
    "Paste": "붙여넣기",
    "Pastes it": "붙여넣기",
    "Pasting": "붙여넣기",
    "Pin": "고정",
    "Privacy": "개인정보",
    "Reopen to the last page": "마지막으로 본 화면으로 열기",
    "Saved": "저장된 항목",
    "The notch opens to what's going on: music while it plays, Claude while it works.": "노치를 열면 상황에 맞는 화면이 나와요. 음악이 재생 중이면 음악, Claude가 작업 중이면 Claude.",
    "The notch opens where you left it. A Claude permission request still comes first.": "노치를 열면 마지막으로 본 화면이 나와요. Claude 권한 요청은 그래도 먼저 보여줘요.",
    "To paste into the app you're using, dancove presses ⌘V for you, which needs Accessibility access. Without it, items are copied and you paste them yourself.": "지금 쓰는 앱에 바로 붙여넣으려면 dancove가 ⌘V를 대신 눌러야 해서 손쉬운 사용 권한이 필요해요. 권한이 없으면 복사만 되고 붙여넣기는 직접 하시면 돼요.",
    "Unpin": "고정 해제",
    "items": "항목",
    "%@ wants to use %@": "%1$@ · %2$@ 사용 요청",
    "%lld percent": "%lld퍼센트",
    "%lld waiting": "%lld개 대기 중",
    "%lld working": "%lld개 작업 중",
    "%lld%% remaining": "%lld%% 남음",
    "%lldh": "%lld시간",
    "%lldh %lldm": "%lld시간 %lld분",
    "%lldm": "%lld분",
    "%lldm %llds": "%lld분 %lld초",
    "%llds": "%lld초",
    "A Dynamic Island for your Mac's notch — with Claude Code built in.": "Mac 노치를 위한 다이내믹 아일랜드 — Claude Code까지 한곳에서.",
    "API overloaded": "API 과부하",
    "About": "정보",
    "Access": "접근 권한",
    "Accessibility": "손쉬운 사용",
    "Account on hold": "계정 보류됨",
    "Active sessions": "진행 중인 세션",
    "Agent: %@": "에이전트: %@",
    "All day": "종일",
    "Allow": "허용",
    "Allow %@?": "%@ 허용할까요?",
    "Allow Calendar Access": "캘린더 접근 허용",
    "Allow…": "허용…",
    "Always": "항상 허용",
    "Always Allow": "항상 허용",
    "Announce headphones and speakers": "헤드폰·스피커 연결 알림",
    "Answer from the notch": "노치에서 응답하기",
    "Apply": "적용",
    "Audio output": "오디오 출력",
    "Authentication failed": "인증 실패",
    "Background agent finished": "백그라운드 에이전트 완료",
    "Battery": "배터리",
    "Battery %lld percent": "배터리 %lld퍼센트",
    "Battery & Devices": "배터리 및 기기",
    "Billing issue": "결제 문제",
    "Calendar": "캘린더",
    "Charging": "충전 중",
    "Claude Code Settings…": "Claude Code 설정…",
    "Claude Code in your notch": "노치 속 Claude Code",
    "Claude finished": "Claude 작업 완료",
    "Claude is waiting for you": "Claude가 답을 기다려요",
    "Claude needs permission": "Claude가 권한을 요청해요",
    "Claude stopped": "Claude가 멈췄어요",
    "Clear Finished Sessions": "끝난 세션 지우기",
    "Click the notch to expand it.": "노치를 클릭하면 펼쳐져요.",
    "Compacting context…": "컨텍스트 압축 중…",
    "Connect Claude Code in Settings to get notified when Claude needs you.": "설정에서 Claude Code를 연결하면 Claude가 찾을 때 알려 드려요.",
    "Connected": "연결됨",
    "Connecting": "연결 중",
    "Connection": "연결",
    "Connectivity": "기기 연결",
    "Deny": "거부",
    "Display": "디스플레이",
    "Display & Sound": "디스플레이 및 사운드",
    "Displays": "디스플레이",
    "Done": "완료",
    "Editing": "편집 중",
    "Editing %@": "%@ 편집 중",
    "Editing notebook": "노트북 편집 중",
    "Enable Claude integration": "Claude 연동 사용",
    "Every Claude turn casts a line. Tool calls are nibbles, and when Claude finishes you reel in a catch. Longer, busier turns bring rarer fish.":
        "Claude가 작업을 시작하면 낚싯대를 던져요. 도구를 쓸 때마다 입질이 오고, 작업이 끝나면 물고기를 낚아 올려요. 오래, 바쁘게 일할수록 희귀한 물고기가 잡혀요.",
    "Expand on hover": "마우스를 올리면 펼치기",
    "Failed — %@": "실패 — %@",
    "Fetching": "가져오는 중",
    "Fetching %@": "%@ 가져오는 중",
    "Finding %@": "%@ 찾는 중",
    "Finding files": "파일 찾는 중",
    "General": "일반",
    "Granted": "허용됨",
    "Grant…": "허용…",
    "Haptic feedback": "햅틱 피드백",
    "Hide from screen recordings": "화면 녹화에서 숨기기",
    "Hide in full screen": "전체 화면에서 숨기기",
    "Hit output limit": "출력 한도 도달",
    "Hooks": "훅",
    "Hover delay": "호버 지연",
    "Hover the notch to open it": "노치에 마우스를 올려 열어 보세요",
    "Idle": "대기 중",
    "In %lld min": "%lld분 후",
    "Inspired by Alcove and NotchNook.": "Alcove와 NotchNook에서 영감을 받았어요.",
    "Install Hooks": "훅 설치",
    "Installed": "설치됨",
    "Interaction": "상호작용",
    "Invalid request": "잘못된 요청",
    "Keyboard": "키보드",
    "Language": "언어",
    "Launch at login": "로그인 시 실행",
    "Level": "레벨",
    "Listener": "리스너",
    "Listening on 127.0.0.1:%@": "127.0.0.1:%@에서 수신 중",
    "Live Activities": "실시간 현황",
    "Low Battery": "배터리 부족",
    "Low battery alerts": "배터리 부족 알림",
    "Media bridge": "미디어 브리지",
    "Model not found": "모델을 찾을 수 없음",
    "Needs permission": "권한 필요",
    "Needs update": "업데이트 필요",
    "No events": "일정 없음",
    "Not granted": "허용 안 됨",
    "Not installed": "설치 안 됨",
    "Nothing Playing": "재생 중인 항목 없음",
    "Notifications": "알림",
    "Now Playing": "지금 재생 중",
    "Now · until %@": "진행 중 · %@까지",
    "On battery": "배터리 사용 중",
    "Open": "열기",
    "Open %@": "%@ 열기",
    "Open source app": "재생 중인 앱 열기",
    "Permission": "권한",
    "Permission requests": "권한 요청",
    "Play a sound": "소리 재생",
    "Play something in Music, Spotify or a browser": "음악, Spotify 또는 브라우저에서 재생해 보세요",
    "Playing": "재생 중",
    "Plug in soon or turn on Low Power Mode.": "곧 충전하거나 저전력 모드를 켜 주세요.",
    "Plugged in": "전원 연결됨",
    "Port": "포트",
    "Power": "전원",
    "Preview Charging Activity": "충전 알림 미리보기",
    "Preview Claude Notification": "Claude 알림 미리보기",
    "Preview Connection": "연결 알림 미리보기",
    "Preview Display HUD": "디스플레이 HUD 미리보기",
    "Preview Notification": "알림 미리보기",
    "Preview Sound HUD": "사운드 HUD 미리보기",
    "Quit dancove": "dancove 종료",
    "Rate limited": "요청 한도 초과",
    "Reading": "읽는 중",
    "Reading %@": "%@ 읽는 중",
    "Relaunch Now": "지금 다시 시작",
    "Relaunch dancove to switch languages.": "언어를 바꾸려면 dancove를 다시 시작하세요.",
    "Remove": "빼기",
    "Replace system volume & brightness HUD": "시스템 음량·밝기 HUD 대체",
    "Running agent": "에이전트 실행 중",
    "Running command": "명령 실행 중",
    "Searching": "검색 중",
    "Searching web": "웹 검색 중",
    "Searching web: %@": "웹 검색: %@",
    "Searching “%@”": "“%@” 검색 중",
    "See when Claude is working, get notified when it finishes or needs you, and answer permission requests without switching apps.":
        "Claude가 일하는 모습을 보고, 끝나거나 도움이 필요할 때 알림을 받고, 앱을 바꾸지 않고도 권한 요청에 답하세요.",
    "See your events here": "여기서 일정을 확인하세요",
    "Server error": "서버 오류",
    "Settings": "설정",
    "Settings…": "설정…",
    "Show Now Playing live activity": "지금 재생 중 표시",
    "Show a live activity while Claude works": "Claude가 일하는 동안 표시",
    "Show calendar in the notch": "노치에 캘린더 표시",
    "Show charging activity": "충전 상태 표시",
    "Show menu bar icon": "메뉴 막대 아이콘 표시",
    "Show on all displays": "모든 디스플레이에 표시",
    "Show percentage": "퍼센트 표시",
    "Show waveform": "파형 표시",
    "Shows the device with its battery when audio switches to AirPods, Bluetooth or AirPlay devices.":
        "오디오가 AirPods, Bluetooth, AirPlay 기기로 바뀌면 기기와 배터리를 보여 줘요.",
    "Something went wrong": "문제가 발생했어요",
    "Sound": "사운드",
    "Source": "소스",
    "Status": "상태",
    "Stay quiet while Claude's app is in front": "Claude 앱이 앞에 있으면 조용히",
    "Stopped": "중지됨",
    "Swipe down on the notch to open it or switch activities, swipe up to close, swipe sideways to skip tracks.":
        "노치에서 아래로 쓸면 열리거나 활동이 바뀌고, 위로 쓸면 닫히고, 옆으로 쓸면 곡이 넘어가요.",
    "System": "시스템",
    "Thinking…": "생각 중…",
    "This day is clear": "오늘은 일정이 없어요",
    "Tint with album artwork": "앨범 아트 색으로 물들이기",
    "Trackpad gestures": "트랙패드 제스처",
    "Unavailable": "사용할 수 없음",
    "Untitled": "제목 없음",
    "Update": "업데이트",
    "Updating tasks": "할 일 갱신 중",
    "Version %@": "버전 %@",
    "Wait for an answer": "응답 대기 시간",
    "Waiting for you": "응답 대기 중",
    "Welcome to dancove": "dancove에 오신 걸 환영해요",
    "When Claude finishes": "Claude가 작업을 마쳤을 때",
    "When Claude needs permission or input": "Claude가 권한이나 입력이 필요할 때",
    "When a turn fails": "작업이 실패했을 때",
    "When the app running Claude isn't in front, dancove holds the request and shows Allow / Deny in the notch. If you don't answer in time, or switch to that app, Claude asks in its own window as usual.":
        "Claude를 실행 중인 앱이 앞에 없으면 dancove가 요청을 잠시 붙잡고 노치에 허용 / 거부를 보여 줘요. 시간 안에 답하지 않거나 그 앱으로 전환하면 평소처럼 Claude 창에서 물어봐요.",
    "Works with Music, Spotify, browsers and any app that reports to Control Center.": "음악, Spotify, 브라우저 등 제어 센터에 표시되는 모든 앱과 함께 동작해요.",
    "Writing": "작성 중",
    "Writing %@": "%@ 작성 중",
    "app": "앱",
    "dancove Settings": "dancove 설정",
    "dancove adds small hooks to ~/.claude/settings.json that forward Claude's events to 127.0.0.1 with curl, and stay silent when dancove isn't running. Your other settings are kept, and the previous file is saved as settings.json.dancove-backup. Sessions that are already running pick up the hooks after a restart.":
        "dancove는 ~/.claude/settings.json에 작은 훅을 추가해 Claude의 이벤트를 curl로 127.0.0.1에 전달해요. dancove가 꺼져 있으면 아무 일도 하지 않아요. 다른 설정은 그대로 두고, 기존 파일은 settings.json.dancove-backup으로 저장해요. 이미 실행 중인 세션은 다시 시작해야 훅이 적용돼요.",
    "dancove listens for the volume and brightness keys and draws its own HUD in the notch. Nothing else is read.":
        "dancove는 음량·밝기 키만 감지해 노치에 자체 HUD를 그려요. 그 밖의 입력은 읽지 않아요.",
    "now": "방금",
    "%@s": "%@초",

    # To-dos
    "%lld done": "%lld개 완료",
    "A page beside the calendar. Click “New To-do” to type; the notch borrows the keyboard only while you type and hands it back when it closes.":
        "캘린더 옆 페이지예요. “새로운 할 일”을 눌러 입력하세요. 노치는 입력하는 동안에만 키보드를 빌리고, 닫히면 원래 앱으로 돌려줘요.",
    "All done": "모두 끝냈어요",
    "Calendar & To-dos": "캘린더 및 할 일",
    "Clear Completed": "완료 항목 지우기",
    "Delete": "삭제",
    "Edit": "편집",
    "Jot things down without leaving what you're doing.": "하던 일을 멈추지 않고 바로 적어 두세요.",
    "Mark as Done": "완료로 표시",
    "Mark as Not Done": "미완료로 표시",
    "Mark as done": "완료로 표시",
    "Mark as not done": "미완료로 표시",
    "New To-do": "새로운 할 일",
    "Nothing yet": "아직 없어요",
    "Show to-dos in the notch": "노치에 할 일 표시",
    "To-dos": "할 일",
    "left": "남았어요",

    # Agents
    "%lld turns · %@": "%lld회 · %@",
    "+%lld more": "+%lld개 더",
    "Agents": "에이전트",
    "All quiet": "모두 쉬는 중",
    "Start Claude or Codex anywhere — what they're doing shows up here.": "어디서든 Claude나 Codex를 시작하세요. 하는 일이 여기에 나타나요.",
    "Today": "오늘",
    "Today %lld · %@": "오늘 %lld회 · %@",
    "working": "작업 중",
    "Codex finished": "Codex 작업 완료",
    "Codex needs approval": "Codex가 승인을 요청해요",
    "Codex stopped": "Codex가 멈췄어요",
    "Detect Claude app, IDE and CLI sessions": "Claude 앱·IDE·CLI 세션 자동 감지",
    "Detect Codex sessions": "Codex 세션 감지",
    "Detection": "감지",
    "Follows the session files in ~/.claude/projects and ~/.codex/sessions, so working status and finished alerts need no setup. Answering permission requests from the notch needs the hooks.":
        "~/.claude/projects와 ~/.codex/sessions의 세션 파일을 따라가서, 설정 없이도 작업 상태와 완료 알림을 보여 줘요. 노치에서 권한 요청에 답하려면 훅이 필요해요.",
    "Choose a port between 1024 and 65535.": "1024에서 65535 사이의 포트를 고르세요.",
    "~/.claude/settings.json could not be parsed: %@. Fix the file and try again.": "~/.claude/settings.json을 읽을 수 없어요: %@. 파일을 고친 뒤 다시 시도하세요.",

    # Rarity
    "Normal": "노말",
    "Legendary": "전설",

    # Fish

}

# Keys that read the same in Korean (numbers, names, symbols).
SAME = {
    "%@ · %@", "%@ — %@", "%lld", "%lld / %lld", "%lld%%", "%lld/%lld", "?", "AirPlay", "Bluetooth", "Claude",
    "English", "NEW", "dancove", "· %@", "한국어", "", "Codex",
}

# English plural variants.
EN_PLURALS = {
    "%lld items": ("%lld item", "%lld items"),
    "Claude: %lld sessions": ("Claude: %lld session", "Claude: %lld sessions"),
}


def unit(value):
    return {"stringUnit": {"state": "translated", "value": value}}


def main():
    catalog = json.loads(CATALOG.read_text())
    # Keys the code no longer uses.
    for key in [k for k, v in catalog["strings"].items() if v.get("extractionState") == "stale"]:
        del catalog["strings"][key]
    missing = []
    for key, entry in catalog["strings"].items():
        localizations = entry.setdefault("localizations", {})
        if key in KO:
            localizations["ko"] = unit(KO[key])
        elif key in SAME:
            localizations["ko"] = unit(key)
        else:
            missing.append(key)
        if key in EN_PLURALS:
            one, other = EN_PLURALS[key]
            localizations["en"] = {"variations": {"plural": {"one": unit(one), "other": unit(other)}}}
    CATALOG.write_text(json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=True) + "\n")
    if missing:
        print("Missing Korean translations:", file=sys.stderr)
        for key in missing:
            print("  " + key, file=sys.stderr)
        sys.exit(1)
    print(f"Translated {len(catalog['strings'])} keys.")


if __name__ == "__main__":
    main()
